### ISSUE TITLE
"Unknown textgrid format" with working TextGrid

### ISSUE THREAD

**Issue by maf654321** [bbTomas/rPraat#1]
First of all, thanks for this package, I've found it immensely helpful. But I'm working now with a TextGrid I've recently created in Praat and for some reason `tg.read("SpeakerH_mono.TextGrid")`  is giving me the error:
```{r}
> tg.read("SpeakerH_mono.TextGrid")
Error in tg.read_lines(flines, find) : Unknown textgrid format.
```
Looking at the file and where error appears in your code, I still can't figure out what's wrong with the file, as both Praat and another R package for reading TextGrids (`textgRid`) read the file fine. Attached is the TextGrid in question, with a .txt file extension for GitHub's sake. I appreciate the help!
[SpeakerH_mono.txt](https://github.com/bbTomas/rPraat/files/2934223/SpeakerH_mono.txt)

**Comment by bbTomas** [comment]
Hello, the default encoding is UTF-8. Your file is in UTF-16 encoding. Please, read your file using this command:
`tg <- tg.read("SpeakerH_mono.txt", encoding = "UTF-16")`

Thank you for using rPraat.
Tomas

**Comment by maf654321** [comment]
Oh, whoops. Should have thought of that. Thanks for the quick response!
