### ISSUE TITLE
Read Pitch object does not work

### ISSUE THREAD

**Issue by stefanocoretta** [bbTomas/rPraat#2]
Hello! I tried importing a Pitch object but a "Unknown Pitch format" is issued.

The error is raised at this line:

https://github.com/bbTomas/rPraat/blob/eda135cd3aca39832a013e250c6583b5f27edeb5/R/pitch.R#L113

I think `frame []:` should be `frames []:`.

This is the head of my Pitch object file:

```
File type = "ooTextFile"
Object class = "Pitch 1"

xmin = 0 
xmax = 4.481451247165533 
nx = 445 
dx = 0.01 
x1 = 0.020725623582766525 
ceiling = 600 
maxnCandidates = 15 
frames []: 
    frames [1]:
        intensity = 0.022695415175049312 
        nCandidates = 15 
        candidates []: 
            candidates [1]:
                frequency = 0 
                strength = 0 
            candidates [2]:
                frequency = 17230.574041555315 
                strength = 0.9202630379132928 
            candidates [3]:
                frequency = 9157.789842534052 
                strength = 0.8802104873742741 
            ...
```

Praat 6.1.38. macOS 11.2.1 (20D74).

**Comment by bbTomas** [comment]
Thank you for the discovery. I have fixed this issue in v1.3.2-1 just now.
Funny, Praat has been going through big changes recently. New logo 🤦‍♂️, frame -> frames and candidate -> candidates in .Pitch file, nFormants -> numberOfFormants in .Formant file 🤣
