### ISSUE TITLE
Avanced pitch settings through rPraat

### ISSUE THREAD

**Issue by llorensmai** [bbTomas/rPraat#3]
Hi! I really love this package, so thank you first and foremost. I'm having a "personal" issue that may be more widespread but maybe not. What I need: to obtain pitch information (e.g. meanf0, maxf0) from labeled intervals on a tier. The catch: I need the advanced pitch settings from Praat to be different from the standards. Specifically, I need the pitch information to be obtained with a voicing threshold level set at 0.7 (standard is 0.45, I believe).
I've tried doing this with Praat scripts and have failed, though I'm not a great Praat scripter so that isn't saying much. I feel much more comfortable in R, but I can't quite figure out if this is something rPraat could even deal with. 
So maybe this is an idea, or maybe just a question. Any insight would be greatly appreciated. Thanks again -

**Comment by bbTomas** [comment]
Hi, if you have a Pitch object, you can read it into rPraat using pitch.read() function. It contains more information than a PitchTier object, see pitch.sample()
Pitch object is in a frame format by default and you can convert it to an array format:
pitch <- pitch.toArray(pitch.sample())
Then, you can access pitch$strengthArray to get intensity of each point and pitch$t is a vector of corresponding time instances.
Using these informations, you can find time intervals of your interest.
Hope this helps,
Tomas

**Comment by llorensmai** [comment]
Yes this is very helpful, thanks so much!
